# Generated by Django 5.1.4 on 2024-12-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50, verbose_name='Unit of Measurement')),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='CustomerCashReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default='Cash Received')),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='accounts.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Cash Received',
                'db_table': 'customer_cash_received',
            },
        ),
        migrations.CreateModel(
            name='Khata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatas', to='roznamcha.business')),
            ],
            options={
                'verbose_name_plural': 'Khata',
                'db_table': 'khata',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('balance_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('khata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='roznamcha.khata')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Roznamcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_type', models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out')], max_length=10)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roznamchas', to='roznamcha.account')),
                ('khata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roznamchas', to='roznamcha.khata')),
            ],
            options={
                'verbose_name_plural': 'Roznamcha',
                'db_table': 'roznamcha',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='roznamcha.product')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='roznamcha.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounts.supplier')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='SupplierCashPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('cash_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default='Cash Paid')),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='accounts.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Cash Paid',
                'db_table': 'supplier_cash_paid',
            },
        ),
    ]
