# Generated by Django 5.2.7 on 2025-10-04 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum credit allowed', max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_sms_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_portal_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_terms_days',
            field=models.IntegerField(default=30, help_text='Payment due in days'),
        ),
        migrations.AddField(
            model_name='account',
            name='portal_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='portal_access_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='preferred_payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_account_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('RETAIL', 'Retail Shop'), ('WHOLESALE', 'Wholesale'), ('SERVICE', 'Service Provider'), ('MANUFACTURING', 'Manufacturing'), ('TRADING', 'Trading Company'), ('OTHER', 'Other')], default='RETAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='easypaisa_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='enable_easypaisa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='enable_jazzcash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='enable_raast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='jazzcash_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='ntn_number',
            field=models.CharField(blank=True, help_text='National Tax Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='raast_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='strn_number',
            field=models.CharField(blank=True, help_text='Sales Tax Registration Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(default='Asia/Karachi', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, help_text='CNIC without dashes (13 digits)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_sms_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_whatsapp_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Business Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant')], default='OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_type',
            field=models.CharField(choices=[('DEBIT', 'Receivable (Customer owes us)'), ('CREDIT', 'Payable (We owe them)')], max_length=10),
        ),
        migrations.CreateModel(
            name='BusinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY_SUMMARY', 'Daily Summary'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('PROFIT_LOSS', 'Profit & Loss'), ('CASH_FLOW', 'Cash Flow'), ('CUSTOMER_AGING', 'Customer Aging Report')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.business')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_used', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_logs', to='accounts.account')),
            ],
            options={
                'db_table': 'customer_portal_access',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due Reminder'), ('PAYMENT_OVERDUE', 'Payment Overdue Alert'), ('PAYMENT_RECEIVED', 'Payment Received Confirmation'), ('ACCOUNT_STATEMENT', 'Account Statement'), ('WELCOME', 'Welcome Message')], max_length=20)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message_template', models.TextField(help_text='Use {name}, {amount}, {due_date} placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='accounts.business')),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('business', 'template_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.business')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash'), ('RAAST', 'RAAST'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.business')),
            ],
            options={
                'db_table': 'payment_methods',
                'unique_together': {('business', 'method_type', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.business')),
                ('roznamcha_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accounts.roznamcha')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymentmethod')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
