# Generated by Django 5.2.7 on 2025-10-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='PKR', max_length=3)),
                ('fiscal_year_start', models.DateField()),
                ('enable_inventory', models.BooleanField(default=True)),
                ('enable_gst', models.BooleanField(default=False)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.business')),
            ],
            options={
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
